version: "3"
services:
  # # React Frontend
  # gppa_frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: gppa_frontend
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "3000:3000"

  # PHP Backend Service
  gppa_php:
    build:
      args:
        user: www-data
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    container_name: gppa_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: gppa_php
      SERVICE_TAGS: dev
      APP_NAME: gppa
      APP_ENV: dev
      APP_DEBUG: "true"
      APP_URL: http://localhost
      LOG_CHANNEL: stack
      DB_CONNECTION: mysql
      DB_HOST: gppa_db
      DB_PORT: 3306
      DB_DATABASE: gppa
      DB_USERNAME: gppa_user
      DB_PASSWORD: gppa
    working_dir: /var/www
    volumes:
      - app-volume:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network

  # Nginx Service
  gppa_webserver:
    image: nginx:alpine
    container_name: gppa_webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - gppa_php
      - gppa_db
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app-volume:/var/www
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - app-network

  # MySQL Service
  gppa_db:
    image: mysql:5.7.22
    container_name: gppa_db
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: gppa
      MYSQL_USER: gppa_user
      MYSQL_PASSWORD: gppa
      MYSQL_ROOT_PASSWORD: gppa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge

# Docker Volumes
volumes:
  app-volume:
    driver: local
  dbdata:
    driver: local
